[workspace]
resolver = "3"
members = [
    "guest-adder-rs",
    "guest-interfaced-adder-rs",
    "guest-kv-store-rs",
    "host-command-component",
    "host-rs"
]

[workspace.dependencies]
wit-bindgen = "0.48.0"
wit-bindgen-rt = { version = "0.44.0" }